[phases.install]
cmds = [
  "dotnet restore src/CoreApi/CoreApi.csproj"
]

[phases.build]
cmds = [
  "dotnet publish src/CoreApi/CoreApi.csproj -c Release -o out"
]

[start]
cmd = "ASPNETCORE_URLS=http://0.0.0.0:$PORT ./out/CoreApi"