using Core.Domain.Exceptions;
using Core.Domain.Interfaces;
using Core.Infrastructure;

namespace Core.Application.UseCases.Auth.Register;

// The Handler contains all the business logic for the Register use case.
// It depends on IUserRepository (an interface, not a concrete class), following the
// Dependency Inversion Principle — this allows the handler to be tested without a real database.
public class RegisterHandler
{
    private readonly IUserRepository _userRepository;

    public RegisterHandler(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    public async Task HandleAsync(RegisterCommand command, CancellationToken cancellationToken = default)
    {
        // Step 1 — Duplicate check: abort early if the email is already registered.
        // The operation is cancelled before any write happens.
        var existing = await _userRepository.GetByEmailAsync(command.Email, cancellationToken);
        if (existing is not null)
            throw new EmailAlreadyTakenException(command.Email);

        // Step 2 — Build the User entity.
        // The password is hashed with BCrypt here, so the raw password never reaches the database.
        // The Id is generated by the application layer, not delegated to the database.
        var user = new User
        {
            Id = Guid.NewGuid(),
            Name = command.Name,
            Email = command.Email,
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(command.Password),
            CreatedAt = DateTime.UtcNow
        };

        // Step 3 — Persist the new user via the repository abstraction.
        await _userRepository.AddAsync(user, cancellationToken);
    }
}
